myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # General
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),

    # User Management
    path('create-user/', views.create_user, name='create-user'),
    path('show-users/', views.show_users, name='show-users'),

    # Courses
    path('courses/', views.course_list, name='course-list'),
    path('courses/create/', views.create_course, name='create-course'),
    path('courses/<int:course_id>/', views.course_detail, name='course-detail'),
    path('courses/<int:course_id>/edit/', views.edit_course, name='edit-course'),
    path('courses/<int:course_id>/delete/', views.delete_course, name='delete-course'),

    # Videos
    path('courses/<int:course_id>/videos/', views.video_list, name='video-list'),
    path('courses/<int:course_id>/videos/add/', views.add_video, name='add-video'),
    path('courses/<int:course_id>/add-video/', views.add_video, name='add-video'),
    path('courses/<int:course_id>/videos/<int:video_id>/edit/', views.edit_video, name='edit-video'),
    path('courses/<int:course_id>/videos/<int:video_id>/delete/', views.delete_video, name='delete-video'),
    path('courses/<int:course_id>/videos/<int:video_id>/', views.video_detail, name='video-detail'),





    path('courses/<int:course_id>/grant-access/', views.grant_course_access, name='grant-course-access'),

    # PDFs
    path('pdfs/', views.pdf_list, name='pdf-list'),
    path('upload-pdf/', views.upload_pdf, name='upload-pdf'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
    
from datetime import datetime, timedelta

class User(AbstractUser):
    username = models.CharField(max_length=200, null=True,unique=True)
    subpassword = models.TextField(null=True)
    email = models.EmailField(verbose_name="Email", null=True, unique=True, max_length=100)
    
    USERNAME_FIELD = 'username'

class Course(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    video_file = models.FileField(upload_to='video/%y')
    is_available = models.BooleanField(default=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='videos', default=None, null = True)


    def __str__(self):
        return self.title

class PDFDocument(models.Model):    
    pdf_file = models.FileField(upload_to='pdf')

    def __str__(self):
        return self.pdf_file.name

class UserCourseAccess(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='accesses')
    expiration_date = models.DateTimeField()

    def __str__(self):
        return f"{self.user.username} - {self.course.title}"
       
class Comment(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.text[:20]}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AdilgazyEdu</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" 
              integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    </head>
    
    <body>
        <!-- Header Section -->
        <header class="header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}">AdilgazyEdu</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ms-auto">
                            <!-- General Navigation Links -->
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" 
                                   href="{% url 'home' %}">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" 
                                   href="{% url 'about' %}">Информация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'course-list' %}active{% endif %}" 
                                   href="{% url 'course-list' %}">Курсы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'pdf-list' %}active{% endif %}" 
                                   href="{% url 'pdf-list' %}">Документы</a>
                            </li>

                            <!-- Conditional Links for Authenticated Users -->
                            {% if user.is_authenticated %}
                                {% if user.is_staff %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'show-users' %}active{% endif %}" 
                                           href="{% url 'show-users' %}">Пользователи</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'create-course' %}active{% endif %}" 
                                           href="{% url 'create-course' %}">Создать курс</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'upload-pdf' %}active{% endif %}" 
                                           href="{% url 'upload-pdf' %}">Загрузить документ</a>
                                    </li>
                                {% endif %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'login' %}">Авторизация</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main Content Section -->
        <main class="container mt-4">
            {% block content %}
            {% endblock %}
        </main>

        <!-- Footer Section -->
        

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" 
                integrity="sha384-pprn3073KE6tl6Wm9KWk/Nqf4Mt6a0YQ4ZUgq7Nf1rtEjrHl8oI5Pj9jjyFh1zW6" 
                crossorigin="anonymous"></script>
    </body>
</html>

templates/course_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ course.title }}</h1>
<p>{{ course.description }}</p>
<h2>Videos:</h2>
<ul>
    {% for video in videos %}
    <li>{{ video.title }}: {{ video.description }}</li>
    {% endfor %}
</ul>
{% endblock %}

templates/course_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'courses.css' %}">

<div class="main-container">
    <div class="head-part">
        <h1 class="page-title">Courses</h1>
        {% if user.is_staff %}
        <a href="{% url 'create-course' %}" class="access_button">Create New Course</a>
        {% endif %}
    </div>

    <div class="courses-container">
        {% if courses %}
        <div class="course-list">
            {% for course in courses %}
            <div class="course-card">
                <a href="{% url 'video-list' course.id %}" class="course-link">
                    <div class="course-content">
                        <h3 class="course-title">{{ course.title }}</h3>
                        <p class="course-description">{{ course.description|truncatewords:30 }}</p>
                        {% if user.is_staff %}
                        <p class="course-status available">
                            Available
                        </p>
                        {% endif %}
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p class="no-courses">No courses available. Click "Create New Course" to add one.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/create_user.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Customer Orders</title>
    <link rel="stylesheet" type="text/css" href="{% static 'createuser.css' %}">
</head>


<body>
    
    <div class="container">
        <h1>Create New User</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
                <label for="login">Login:</label>
                <input type="text" id="login" name="login" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="btn">Create User</button>
        </form>
        
        {% if alert %}
        <div class="alert">
            {{ alert }}
        </div>
        {% endif %}
    </div>
</body>
</html>
{% endblock %}

templates/delete_course.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Course</h1>
<p>Are you sure you want to delete the course "{{ course.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <a href="{% url 'course-list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/delete_video.html
{% extends 'base.html' %}

{% block content %}
<div class="delete-confirmation">
    <h1>Delete Video</h1>
    <p>Are you sure you want to delete the video <strong>{{ video.title }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'video-list' course.id %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/edit_video.html
{% extends 'base.html' %}

{% block content %}
<div class="video-form-container">
    <h1 class="page-title">Edit Video in {{ course.title }}</h1>
    <form method="post" enctype="multipart/form-data" class="video-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title:</label>
            <input type="text" id="id_title" name="title" class="form-control" value="{{ video.title }}" required>
        </div>
        <div class="form-group">
            <label for="id_description">Description:</label>
            <textarea id="id_description" name="description" rows="4" class="form-control" required>{{ video.description }}</textarea>
        </div>
        <div class="form-group">
            <label for="id_video_file">Upload Video:</label>
            <input type="file" id="id_video_file" name="video_file" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Update Video</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'style.css' %}">

<title>EduPage</title>


 <section class="home">
    <div class="home-content">
        <h1>Welcome to EDU</h1>
        <div class="btn-box">
            <a href="{% url 'course-list' %}">Courses</a>
            <a href="#">Telegram</a>
        </div>
    </div>
 </section>

 <script>
    document.addEventListener("DOMContentLoaded", function() {
        const message = "{{ message|escapejs }}";
        if (message) {
            showAlert(message);
        }
    });

    function showAlert(message) {
        const alertBox = document.createElement('div');
        alertBox.className = 'custom-alert';
        alertBox.innerHTML = `<p>${message.replace(/\\n/g, '<br>')}</p><button onclick="this.parentElement.style.display='none';">Close</button>`;
        document.body.appendChild(alertBox);
    }
</script>
 {% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'login.css' %}">

<header class="header">
  <nav class="navbar">
      <a href="{% url 'home' %}" class="active">Home</a>
      <a href="#">About</a>
      <a href="{% url 'course-list' %}">Courses</a>
      <div class="signin">
          <a href="{% url 'login' %}">Register</a>
      </div>
  </nav>
</header>

<div class="login-container">
  <div class="card">
      <div class="card-header">Login</div>
      <div class="card-body">
          {% if error_message %}
              <div class="alert alert-danger" role="alert">{{ error_message }}</div>
          {% endif %}
          <form method="post">
              {% csrf_token %}
              <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" class="form-control" id="username" name="username" required placeholder="Type your username" required>
              </div>
              <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" id="password" name="password" required placeholder="Type your password" required>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Login</button>
          </form>
      </div>
  </div>
</div>
{% endblock %}

templates/pdf_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pdfs.css' %}">

<title>AdilgazyEDU</title>

<div class="main-container">
    <h1 class="page-title">PDF Documents</h1>
    <div class="pdfs-container">
        {% for pdf in pdfs %}
        <div class="pdf-card">
            <div class="pdf-info">
                <h3 class="pdf-title">{{ pdf.pdf_file.name|slice:":-4" }}</h3>
                <a href="{{ pdf.pdf_file.url }}" class="pdf-link" target="_blank">View PDF</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/show_users.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Customer Orders</title>
    <link rel="stylesheet" type="text/css" href="{% static 'table.css' %}">
</head>


<main class="table" id="customers_table">
    <section class="table__header">
        <h1>User list</h1>
        <a class="user_create" href="{% url 'create-user' %}">Create user</a>
        <div class="input-group">
            <input type="search" name="q" placeholder="Search User..." id="search-input">
            <img src="{% static 'media/search.png' %}" alt="Search">
        </div>
    </section>
    <section class="table__body">
        <table>
            <thead>
                <tr>
                    <th>Id <span class="icon-arrow">&UpArrow;</span></th>
                    <th>Username <span class="icon-arrow">&UpArrow;</span></th>
                    <th>Password <span class="icon-arrow">&UpArrow;</span></th>
                    <th>Is Staff <span class="icon-arrow">&UpArrow;</span></th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.subpassword }}</td>
                    <td>{{ user.is_staff }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
</main>
<script>
    document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.querySelector('#search-input');
    const tableRows = document.querySelectorAll('tbody tr');

    searchInput.addEventListener('input', function () {
        const query = this.value.toLowerCase();

        tableRows.forEach(row => {
            const cells = row.querySelectorAll('td');
            const matches = Array.from(cells).some(cell => cell.textContent.toLowerCase().includes(query));
            row.style.display = matches ? '' : 'none';
        });
    });

    const headers = document.querySelectorAll('thead th');
    headers.forEach(header => {
        header.addEventListener('click', () => {
            const table = header.parentElement.parentElement.parentElement;
            const index = Array.from(header.parentElement.children).indexOf(header);
            const rows = Array.from(table.querySelectorAll('tbody tr'));
            const isAsc = header.classList.toggle('asc');
            const direction = isAsc ? 1 : -1;

            rows.sort((rowA, rowB) => {
                const cellA = rowA.children[index].textContent.trim();
                const cellB = rowB.children[index].textContent.trim();

                return cellA > cellB ? (1 * direction) : (-1 * direction);
            });

            rows.forEach(row => table.querySelector('tbody').appendChild(row));
        });
    });
});

</script>
{% endblock %}

templates/video_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'videos.css' %}">

<title>{{ video.title }} - AdilgazyEDU</title>

<div class="main-container">
    <h1 class="page-title">{{ video.title }}</h1>
    <div class="video-detail-container">
        <video class="video-player-large" controls poster="{{ video.thumbnail.url }}">
            <source src="{{ video.video_file.url }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <p class="video-description-full">{{ video.description }}</p>
    </div>

    <!-- Секция комментариев -->
    <div class="comments-section">
        <h2 class="comments-title">Comments</h2>
        
        <!-- Список комментариев -->
        <div class="comments-list">
            {% for comment in comments %}
            <div class="comment">
                <strong>{{ comment.user.username }}</strong>
                <p>{{ comment.text }}</p>
                <span class="comment-date">{{ comment.created_at|date:"F j, Y, g:i a" }}</span>
            </div>
            {% empty %}
            <p>No comments yet. Be the first to comment!</p>
            {% endfor %}
        </div>

        <!-- Форма добавления комментария -->
        {% if user.is_authenticated %}
        <form method="post" class="comment-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="submit-comment-button">Add Comment</button>
        </form>
        {% else %}
        <p>You must be logged in to post a comment.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/video_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Video</title>
    <link rel="stylesheet" type="text/css" href="{% static 'video_form.css' %}">
</head>

<body>
    <div class="container">
        <h2 class="form-title">Upload Video</h2>
        <form method="post" enctype="multipart/form-data" class="upload-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="upload-button">Upload</button>
        </form>
    </div>
</body>

</html>
{% endblock %}

templates/video_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'videos.css' %}">

<title>AdilgazyEDU</title>

<div class="videos-container">
    <div class="header-section">
        <h1 class="page-title">Videos in {{ course.title }}</h1>
        <a href="{% url 'course-list' %}" class="btn btn-secondary">Back to Courses</a>
        {% if user.is_staff %}
        <a href="{% url 'add-video' course.id %}" class="btn btn-primary">Add Video</a>
        {% endif %}
    </div>

    {% if videos %}
    <div class="video-list">ы
        {% for video in videos %}
        
        <div class="video-card">
            <a href="{% url 'video-detail' course.id video.id %}" class="video-card-link">
                <video class="video-player">
                    <source src="{{ video.video_file.url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                <div class="video-content">
                    <h3 class="video-title">{{ video.title }}</h3>
                    <p class="video-description">{{ video.description|truncatewords:20 }}</p>
                </div>
            </a>
        </div>
        
        {% endfor %}
    </div>
    {% else %}
    <p class="no-videos">No videos available for this course. Add a video to get started!</p>
    {% endif %}
</div>

{% endblock %}